version: "3.7"

services:

  web:
    build:
      context: ./web/
      args:
        - API_URL
    depends_on:
      - server
    ports:
      - "3000:80"

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - LOGLEVEL=warn
      - PORT=3001
      - MASTER_KEY
      - JWT_SECRET
      - CORS_ORIGIN

  db:
    image: mongo:3.4.6
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "27017"]
      interval: 15s
      timeout: 1m
      retries: 4
    ports:
      - 27017:27017
